96 3ª sprint cadastrar pedido
GedelQ/Undefined pull request #100
Opened 2023-12-13 02:46 UTC by GedelQ

2023-12-13 21:04 UTC, Mitisuaki requested changes
Mexer nas coisas que conversamos anteriormente e realizar testes antes de solicitar uma nova review. Qualquer coisa pode me chamar discord e ajudo com o que for necessário

2023-12-13 21:04 UTC, Mitisuaki commented on src/schemas/schemaOrder.js
> +
Na versão final tem que tirar esse comentário

2023-12-13 21:04 UTC, Mitisuaki commented on src/controllers/orderController.js
> +
Arrumar o amount que tem de multiplicar com a quantidade de produtos como conversamos em call

2023-12-15 19:08 UTC, GedelQ commented on src/schemas/schemaOrder.js
> +
Tudo bem!

2023-12-15 19:08 UTC, GedelQ commented on src/controllers/orderController.js
> +
Tudo bem!

2023-12-18 00:52 UTC, merged