Feature/products
GedelQ/Undefined pull request #76
Opened 2023-12-06 14:48 UTC by BrunoSilva96

Correção na parte onde transforma a quantidade de produtos em numeros.

2023-12-06 18:26 UTC, OlivinoHM approved these changes

2023-12-06 23:52 UTC, Mitisuaki requested changes

2023-12-06 23:52 UTC, Mitisuaki commented on src/index.js
Why did you dele the entire index.js? I Don`t think this is right, so or change or explain to me why

2023-12-06 23:52 UTC, Mitisuaki commented on src/routes/routers.js
Please remove all ;

2023-12-07 22:23 UTC, OlivinoHM requested changes
Enviar só os arquivos que foram alterados, quando for fazer o git add, ao invés de mandar com o (.)ponto, colocar somente o nome dos arquivos que são dependentes da atualização ou criação.
Um atalho que uso é antes de fazer o git add, eu mando um git status, assim copio o caminho dos arquivos necessários.

2023-12-08 00:21 UTC, closed without merging