Bugs fixed/gedel
GedelQ/Undefined pull request #97
Opened 2023-12-12 01:06 UTC by GedelQ

2023-12-12 10:34 UTC, Mitisuaki requested changes
Verifique o Joi para estado se esta certo assim ou realmente deve mudar

2023-12-12 10:34 UTC, Mitisuaki commented on src/schemas/schemaUser.js
> -    "string.base": "O campo CEP deve ser string.",
na verificação de estado não deveria ser "string.estado" ?

2023-12-12 12:02 UTC, GedelQ commented on src/schemas/schemaUser.js
> -    "string.base": "O campo CEP deve ser string.",
Corrigido!

2023-12-12 12:12 UTC, Mitisuaki approved these changes
Aparentemente tudo certo agora

2023-12-14 14:57 UTC, OlivinoHM approved these changes
Ok, verificado!

2023-12-14 14:57 UTC, merged